    INTERFACE 
      FUNCTION ZBQLU01(DUMMY)
        DOUBLE PRECISION :: ZBQLU01
        DOUBLE PRECISION, INTENT(IN) :: DUMMY
      END FUNCTION ZBQLU01
    END INTERFACE 
    
    INTERFACE 
      FUNCTION ZBQLNOR(MU,SIGMA)
        DOUBLE PRECISION :: ZBQLNOR
        DOUBLE PRECISION, INTENT(IN) :: MU, SIGMA
      END FUNCTION ZBQLNOR
    END INTERFACE
